In [2]:
!pip install sqlalchemy
!pip install pymysql

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (3.0.3)
Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 1.3 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [3]:
import sqlalchemy
from sqlalchemy import create_engine
import pandas as pd

In [5]:

# un: student_athletics
# pw: 
# hostname: @shtm-fallprev.mysql.database.azure.com
# databasename: sbu_athletics

# {dbtype}+{driver}://{username}:{password}@{hostname}/{dbname}

# engine = create_engine('mysql+pymysql://student_athletics:INSERTPASSWORDHERE@shtm-fallprev.mysql.database.azure.com/sbu_athletics')
# mysql = the type of the database that you are trying to connect o
# pymysql = the driver


engine = create_engine('mysql+pymysql://student_athletics:INSERTPASSWORDHERE!!@shtm-fallprev.mysql.database.azure.com/sbu_athletics')

In [6]:
df = pd.read_sql_table('analytics_sbusportcounts', engine)
df

      my_row_id  sbu_sport           timestamp table_name  count_value
0             1   Baseball 2024-06-14 18:25:18    kinexon        23965
1             2   Baseball 2024-06-14 18:25:18    hawkins       206479
2             3   Baseball 2024-06-14 18:25:18       vald         2088
3             4   Football 2024-06-14 18:25:18    kinexon       411465
4             5   Football 2024-06-14 18:25:18    hawkins       267990
...         ...        ...                 ...        ...          ...
3681       3682  Womes Lax 2024-09-11 05:12:35    hawkins       202708
3682       3683  Womes Lax 2024-09-11 05:12:35       vald         5148
3683       3684       None 2024-09-11 05:12:35    kinexon      1174072
3684       3685       None 2024-09-11 05:12:35    hawkins       444024
3685       3686       None 2024-09-11 05:12:35       vald        17280

[3686 rows x 5 columns]

In [7]:
df_small = pd.read_sql_query(
    'select * from analytics_sbusportcounts limit 50',  # argument 1 - sql query
    engine                                              #query 2 is the connection string
    )
df_small

            sbu_sport           timestamp table_name  count_value
0            Baseball 2024-06-14 18:25:18    kinexon        23965
1            Baseball 2024-06-14 18:25:18    hawkins       206479
2            Baseball 2024-06-14 18:25:18       vald         2088
3            Football 2024-06-14 18:25:18    kinexon       411465
4            Football 2024-06-14 18:25:18    hawkins       267990
5            Football 2024-06-14 18:25:18       vald         9432
6     Mens Basketball 2024-06-14 18:25:18    kinexon       277352
7     Mens Basketball 2024-06-14 18:25:18    hawkins       119234
8     Mens Basketball 2024-06-14 18:25:18       vald         1572
9            Mens Lax 2024-06-14 18:25:18    hawkins       123883
10           Mens Lax 2024-06-14 18:25:18       vald         2352
11        Mens Soccer 2024-06-14 18:25:18    kinexon       224720
12        Mens Soccer 2024-06-14 18:25:18    hawkins        95146
13        Mens Soccer 2024-06-14 18:25:18       vald         3372
14           Softball 2024-06-14 18:25:18    hawkins        43832
15           Softball 2024-06-14 18:25:18       vald          840
16               Swim 2024-06-14 18:25:18    hawkins        70092
17               Swim 2024-06-14 18:25:18       vald           24
18             Tennis 2024-06-14 18:25:18    hawkins        51853
19             Tennis 2024-06-14 18:25:18       vald          420
20    Track and Field 2024-06-14 18:25:18    kinexon         1809
21    Track and Field 2024-06-14 18:25:18    hawkins        33400
22    Track and Field 2024-06-14 18:25:18       vald         1092
23  Womens Basketball 2024-06-14 18:25:18    kinexon       353910
24  Womens Basketball 2024-06-14 18:25:18    hawkins       178255
25  Womens Basketball 2024-06-14 18:25:18       vald         2232
26      Womens Soccer 2024-06-14 18:25:18    kinexon       370028
27      Womens Soccer 2024-06-14 18:25:18    hawkins       140919
28      Womens Soccer 2024-06-14 18:25:18       vald         3312
29  Womens Volleyball 2024-06-14 18:25:18    kinexon        95806
30  Womens Volleyball 2024-06-14 18:25:18    hawkins        93565
31  Womens Volleyball 2024-06-14 18:25:18       vald         1344
32          Womes Lax 2024-06-14 18:25:18    kinexon       408087
33          Womes Lax 2024-06-14 18:25:18    hawkins       201300
34          Womes Lax 2024-06-14 18:25:18       vald         4896
35               None 2024-06-14 18:25:18    kinexon       735647
36               None 2024-06-14 18:25:18    hawkins       422704
37               None 2024-06-14 18:25:18       vald        14952
38           Baseball 2024-06-14 23:07:59    kinexon        23965
39           Baseball 2024-06-14 23:07:59    hawkins       206479
40           Baseball 2024-06-14 23:07:59       vald         2088
41           Football 2024-06-14 23:07:59    kinexon       411465
42           Football 2024-06-14 23:07:59    hawkins       267990
43           Football 2024-06-14 23:07:59       vald         9432
44    Mens Basketball 2024-06-14 23:07:59    kinexon       277352
45    Mens Basketball 2024-06-14 23:07:59    hawkins       119234
46    Mens Basketball 2024-06-14 23:07:59       vald         1572
47           Mens Lax 2024-06-14 23:07:59    hawkins       123883
48           Mens Lax 2024-06-14 23:07:59       vald         2352
49        Mens Soccer 2024-06-14 23:07:59    kinexon       224720